SELECT
    A.NAME,
    A.START_DATE AS DATETIME
FROM
    (SELECT
        ANIMAL_ID,
        NAME,
        DATETIME AS START_DATE
     FROM
        ANIMAL_INS) AS A
LEFT OUTER JOIN
    (SELECT
        ANIMAL_ID,
        DATETIME AS END_DATE
     FROM 
        ANIMAL_OUTS) AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.END_DATE IS NULL
ORDER BY START_DATE ASC
LIMIT 3
